precision: 32
max_epochs: 80
num_nodes: 1
sync_batchnorm: True
default_root_dir: #${exp_dir}
num_sanity_val_steps: 0
check_val_every_n_epoch: 1
limit_val_batches: 1.0
accumulate_grad_batches: 1
gradient_clip_val: 5.0
accelerator: gpu
use_distributed_sampler: False